version: '3'
services:
  redisAuth:
    image: "redis:latest"
    ports:
      - "${REDIS_AUTH_DOCKER_PORT}:6379"
    networks:
      - net

  redisPosts:
    image: "redis:latest"
    ports:
      - "${REDIS_POSTS_DOCKER_PORT}:6379"
    networks:
      - net

  authpsx:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: ${AUTH_PSX_PASSWORD}
      POSTGRES_USER: ${AUTH_PSX_USER}
      POSTGRES_DB: ${AUTH_PSX_DBNAME}
    volumes:
      - ./scripts/sql/auth/init:/docker-entrypoint-initdb.d
    ports:
      - "${AUTH_PSX_DOCKER_PORT}:5432"
    networks:
      - net

  postspsx:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: ${POSTS_PSX_DBNAME}
      POSTGRES_PASSWORD: ${POSTS_PSX_PASSWORD}
      POSTGRES_USER: ${POSTS_PSX_USER}
    volumes:
      - ./scripts/sql/posts/init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTS_PSX_DOCKER_PORT}:5432"
    networks:
      - net

  nginx:
    image: "nginx:latest"
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - authapp
      - postsapp
    networks:
      - net

  postsapp:
    build:
      context: .
      dockerfile: Dockerfile_posts
    ports:
      - "${POSTS_APP_PORT}:${POSTS_APP_PORT}"
    depends_on:
      - redisAuth
      - redisPosts
      - authpsx
      - postspsx
    env_file:
      ./.env
    networks:
      - net

  authapp:
    build:
      context: .
      dockerfile: Dockerfile_auth
    ports:
      - "${AUTH_APP_PORT}:${AUTH_APP_PORT}"
      - "${AUTH_GRPC_PORT}:${AUTH_GRPC_PORT}"
    depends_on:
      - redisAuth
      - redisPosts
      - authpsx
      - postspsx
    env_file:
      ./.env
    networks:
      - net

networks:
  net:
    driver: bridge